# Generated by Django 4.2.13 on 2024-08-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('adminApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfos',
            name='role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='core.role'),
            preserve_default=False,
        ),
    ]
