# Generated by Django 4.2.13 on 2024-06-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyApp.address'),
            preserve_default=False,
        ),
    ]
