# Generated by Django 4.2.15 on 2024-08-24 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
